### ISSUE TITLE
Sugerencias

### ISSUE THREAD

**Issue by Edwardb11** [DevKendrySoto/login-react#1]
- ```ProtectedRoute``` deberia ir en una caprta de ```routes```  en la misma podria tener un ```router.js``` y colocar la logica que tienes en ```App```.
- Las credenciales deberian ir en una ruta mas especifica podria ser ```/firebase/config.js``` 
- Las Variables de esas credenciales deberian ir en un archivo ```.env```

**Comment by DevKendrySoto** [comment]
Gracias por las observaciones, trabajare en eso
